services:
  - type: web
    name: stock-manager
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: USE_NEON
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: WHATSAPP_WEBHOOK_TOKEN
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_REFRESH_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN_EXPIRY
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: META_GRAPH_API_VERSION
        value: v20.0
      - key: META_APP_ID
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health

